[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=Xvfb :0 -screen 0 1280x720x24
autorestart=true
priority=10

[program:fluxbox]
command=fluxbox
autorestart=true
priority=20
environment=DISPLAY=":0"

[program:x11vnc]
command=x11vnc -display :0 -forever -shared -rfbport 5900 -nopw
autorestart=true
priority=30

[program:novnc]
command=/usr/share/novnc/utils/novnc_proxy --vnc localhost:5900 --listen %(env{PORT})s
autorestart=true
priority=40

[program:firefox]
command=firefox --display=:0 --profile /tmp/firefox-profile
autorestart=true
priority=50
environment=DISPLAY=":0"
